development:
  adapter: async
  # adapter: redis
  # url: redis://localhost:3000

test:
  adapter: async

production:
  adapter: async
  # adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # url: redis://54.168.202.179
  # channel_prefix: Phote-App_production