development:
  # adapter: async
  adapter: redis
  url: redis://localhost:6379
  channel_prefix: Phote-App_production

test:
  adapter: async

production:
  # adapter: async
  adapter: redis
  url: redis://54.168.202.179:6379
  # url: redis://localhost:6379/1
  channel_prefix: Phote-App_production